feat: 'feature'
Feat: 'feature'
fix: 'bug'
Fix: 'bug'
chore: 'chore'
Chore: 'chore'
docs: 'documentation'
Docs: 'documentation'
test: 'test'
Test: 'test'
ci: 'ci'
CI: 'ci'
refactor: 'chore'
Refactor: 'chore'
