name: CI Tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  test-with-summary:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run `poe test-with-summary` [Poe Command Processor]
        uses: ./
        with:
          pr: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: test-with-summary

  test-without-summary:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run `poe test-without-summary` [Poe Command Processor]
        uses: ./
        with:
          pr: ${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: test-without-summary
