name: Format Fix (On-Demand)

on:
  workflow_dispatch:
    inputs:
      # The following 4 inputs are always passed by the Slash Command Dispatch:
      repo:
        description: Repo Name. Ignored.
        type: choice
        required: false
        default: airbytehq/airbyte-enterprise
        options:
          - airbytehq/airbyte-enterprise
      gitref:
        description: Git Ref. Ignored.
        required: false
      comment-id:
        description: Comment ID. Optional.
        required: false
      pr:
        description: PR Number.
        type: number
        required: false

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run-format-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Run `poe format-fix` [Poe Command Processor]
        uses: ./action.yml
        with:
          pr: ${{ github.event.inputs.pr }}
          comment-id: ${{ github.event.inputs.comment-id }}
          github-token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
          command: test
